### ISSUE TITLE
Investigate Storybook alternatives 

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer-app#1057]
Ref:

* https://github.com/tajo/ladle
* https://news.ycombinator.com/item?id=37596842

**Comment by georgefst** [comment]
Storybook was a major annoyance for me a year ago. I still don't _love_ it by any means, but it does seem to have become more stable and I actually think the recent UI changes are a major improvement. Besides, we've been using it a lot less since we have had a working app.

I can understand being concerned about telemetry, however.

**Comment by dhess** [comment]
Yes, I think Ladle doesn't look very interesting and probably wouldn't be worth the effort of a port, versus simply dropping Storybook entirely. It's probably Storybook or nothing.
